services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemstore-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: gemstore-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend